version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: /src/Dockerfile
    volumes:
      - ./models:/workdir/models
    ports:
      - "8000:8000"
      
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default: