version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: /src/Dockerfile
    volumes:
      - ./models:/workdir/models
    ports:
      - "8000:8000"
