stages:
  preprocess_train:
    cmd: python src/data/preprocess.py data/Train/resized_images_N/ data/train_preprocessed_images/
      True
    deps:
    - data/Train/resized_images_N/
    - src/data/preprocess.py
    outs:
    - data/train_preprocessed_images/:
        cache: false
  preprocess_test:
    cmd: python src/data/preprocess.py data/Test/resized_test_images_N/ data/test_preprocessed_images/
      False
    deps:
    - data/Test/resized_test_images_N/
    - src/data/preprocess.py
    outs:
    - data/test_preprocessed_images/:
        cache: false
  train:
    cmd: python src/models/train.py
    deps:
    - data/Train/resized_train.data.v1.txt
    - data/Train/resized_train.gold.v1.txt
    - data/train_preprocessed_images/
    - src/models/conf.py
    - src/models/utils.py
    - src/models/train.py
    outs:
    - models/model.pt
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/Test/en.test.data.v1.1.txt
    - data/Test/en.test.gold.v1.1.txt
    - data/test_preprocessed_images/
    - models/model.pt
    - src/models/conf.py
    - src/models/utils.py
    - src/models/evaluate.py
    metrics:
    - metrics/hits1.metric:
        cache: false
    - metrics/hits3.metric:
        cache: false
    - metrics/mrr.metric:
        cache: false
