global:
  scrape_interval: 10s
  external_labels:
    monitor: 'it-disambiguation-monitor'

scrape_configs:
  - job_name: "fastapi-it"
    # Scrape targets from this job every 5 seconds
    scrape_interval: 5s

    static_configs:
      - targets: ["backend:8000"]