name: Pytest

on:
  push:
    branches:
      - pytest_action
    # paths:
    #   - 'src/**'
    #   - '!src/api/**'
    #   - 'tests/**'
    #   - '!tests/api_testing/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: DVC setup
        uses: iterative/setup-dvc@v1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare data and model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull data/Train
          dvc pull models/model.pt
          dvc repro preprocess_train

      - name: Test dataset
        run: |
          python -m pytest tests/dataset_testing/

      - name: Test preprocessing functions
        run: |
          python -m pytest tests/preprocessing_testing/

      - name: Test model behavior
        run: |
          python -m pytest --disable-warnings tests/behavioral_testing/

      - name: Test APIs
        run: |
          python -m pytest --disable-warnings tests/api_testing/

      # - name: Test model training
      #   run: |
      #     python -m pytest --disable-warnings tests/model_testing/
